services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      DATABASE_URL: mysql://root:${DATABASE_PASSWORD}@localhost:3306/${DATABASE_NAME}
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app
    depends_on:
      - database
    container_name: omnigame_app

  database:
    image: mysql:8
    container_name: omnigame_database
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4h78gJ9y47M4SsTeG93RQcV3DmPtbdXU
      MYSQL_DATABASE: website
      TZ: "Europe/Paris"
    restart: always
